const { PDFDocument, StandardFonts, rgb } = require("pdf-lib");

const money = (amount, currency = "USD") =>
  `${String(currency).toUpperCase()} ${Number(amount || 0).toFixed(2)}`;

const drawLine = (page, y) => {
  page.drawLine({
    start: { x: 48, y },
    end: { x: 547, y },
    thickness: 1,
    color: rgb(0.86, 0.86, 0.86),
  });
};

const drawText = (page, text, x, y, options = {}) => {
  page.drawText(String(text || ""), {
    x,
    y,
    size: options.size || 10,
    font: options.font,
    color: options.color || rgb(0.12, 0.12, 0.12),
    maxWidth: options.maxWidth,
  });
};

const buildInvoicePdf = async ({ purchase, user }) => {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595.28, 841.89]);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const paidAt = purchase.paidAt || purchase.createdAt || new Date();
  const invoiceNumber = purchase.invoiceNumber || purchase._id.toString();
  const buyerName = user?.name || "Customer";
  const buyerEmail = user?.email || "";
  const itemLabel =
    purchase.purchaseType === "chapter" && purchase.chapterTitles?.length
      ? `${purchase.bookTitle} - ${purchase.chapterTitles.join(", ")}`
      : purchase.bookTitle;

  pdfDoc.setTitle(`Invoice ${invoiceNumber}`);
  pdfDoc.setAuthor("Crossed Hearts");
  pdfDoc.setSubject(`Invoice for ${buyerEmail}`);
  pdfDoc.setProducer("Crossed Hearts");
  pdfDoc.setCreator("Crossed Hearts");

  drawText(page, "Crossed Hearts", 48, 780, {
    size: 24,
    font: bold,
    color: rgb(0.08, 0.08, 0.08),
  });
  drawText(page, "Invoice", 470, 784, { size: 18, font: bold });
  drawLine(page, 755);

  drawText(page, "Invoice Number", 48, 720, { font: bold });
  drawText(page, invoiceNumber, 180, 720, { font });
  drawText(page, "Date", 48, 700, { font: bold });
  drawText(page, new Date(paidAt).toLocaleString(), 180, 700, { font });
  drawText(page, "Status", 48, 680, { font: bold });
  drawText(page, purchase.status || "paid", 180, 680, { font });

  drawText(page, "Billed To", 360, 720, { font: bold });
  drawText(page, buyerName, 360, 700, { font });
  drawText(page, buyerEmail, 360, 684, { font });

  drawLine(page, 640);
  drawText(page, "Item", 48, 612, { font: bold });
  drawText(page, "Type", 330, 612, { font: bold });
  drawText(page, "Amount", 465, 612, { font: bold });
  drawLine(page, 596);

  drawText(page, itemLabel, 48, 570, { font, maxWidth: 260 });
  drawText(page, purchase.purchaseType || "book", 330, 570, { font });
  drawText(page, money(purchase.amount, purchase.currency), 465, 570, { font });
  drawLine(page, 540);

  drawText(page, "Total", 390, 510, { font: bold, size: 13 });
  drawText(page, money(purchase.amount, purchase.currency), 465, 510, {
    font: bold,
    size: 13,
  });

  const paymentReference =
    purchase.paymentReference || purchase.razorpayPaymentId || purchase.stripePaymentIntentId;
  if (paymentReference) {
    drawText(page, "Payment Reference", 48, 470, { font: bold });
    drawText(page, paymentReference, 180, 470, { font });
  }

  drawText(page, "Thank you for your purchase.", 48, 120, { font: bold });
  drawText(
    page,
    "This invoice was generated by Crossed Hearts and is valid for your digital purchase records.",
    48,
    102,
    { font, maxWidth: 480 }
  );

  return Buffer.from(await pdfDoc.save());
};

const buildPhysicalOrderInvoicePdf = async ({ order, user }) => {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595.28, 841.89]);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const paidAt = order.updatedAt || order.createdAt || new Date();
  const invoiceNumber = order.orderNumber || order._id.toString();
  const buyerName = order.shippingAddress?.fullName || user?.name || "Customer";
  const buyerEmail = order.shippingAddress?.email || user?.email || "";

  pdfDoc.setTitle(`Invoice ${invoiceNumber}`);
  pdfDoc.setAuthor("Crossed Hearts");
  pdfDoc.setSubject(`Physical order invoice for ${buyerEmail}`);
  pdfDoc.setProducer("Crossed Hearts");
  pdfDoc.setCreator("Crossed Hearts");

  drawText(page, "Crossed Hearts", 48, 780, {
    size: 24,
    font: bold,
    color: rgb(0.08, 0.08, 0.08),
  });
  drawText(page, "Print Order Invoice", 404, 784, { size: 16, font: bold });
  drawLine(page, 755);

  drawText(page, "Invoice Number", 48, 720, { font: bold });
  drawText(page, invoiceNumber, 180, 720, { font });
  drawText(page, "Date", 48, 700, { font: bold });
  drawText(page, new Date(paidAt).toLocaleString(), 180, 700, { font });
  drawText(page, "Status", 48, 680, { font: bold });
  drawText(page, order.paymentStatus || "paid", 180, 680, { font });

  drawText(page, "Ship To", 360, 720, { font: bold });
  drawText(page, buyerName, 360, 700, { font });
  drawText(page, buyerEmail, 360, 684, { font });
  drawText(page, order.shippingAddress?.line1 || "", 360, 668, { font, maxWidth: 180 });
  drawText(
    page,
    [order.shippingAddress?.city, order.shippingAddress?.state, order.shippingAddress?.postalCode]
      .filter(Boolean)
      .join(", "),
    360,
    652,
    { font, maxWidth: 180 },
  );

  drawLine(page, 620);
  drawText(page, "Item", 48, 592, { font: bold });
  drawText(page, "Qty", 360, 592, { font: bold });
  drawText(page, "Amount", 465, 592, { font: bold });
  drawLine(page, 576);

  let y = 550;
  (order.items || []).slice(0, 10).forEach((item) => {
    drawText(page, `${item.title} - ${item.edition || "Standard"}`, 48, y, {
      font,
      maxWidth: 290,
    });
    drawText(page, String(item.quantity || 1), 360, y, { font });
    drawText(
      page,
      money(Number(item.unitPrice || 0) * Number(item.quantity || 1), order.currency),
      465,
      y,
      { font },
    );
    y -= 28;
  });

  drawLine(page, y + 8);
  drawText(page, "Subtotal", 360, y - 22, { font: bold });
  drawText(page, money(order.subtotal, order.currency), 465, y - 22, { font });
  drawText(page, "Shipping", 360, y - 44, { font: bold });
  drawText(page, money(order.shippingFee, order.currency), 465, y - 44, { font });
  drawText(page, "Total", 360, y - 76, { font: bold, size: 13 });
  drawText(page, money(order.total, order.currency), 465, y - 76, {
    font: bold,
    size: 13,
  });

  if (order.paymentReference) {
    drawText(page, "Payment Reference", 48, y - 118, { font: bold });
    drawText(page, order.paymentReference, 180, y - 118, { font });
  }

  drawText(page, "Thank you for your print order.", 48, 120, { font: bold });
  drawText(
    page,
    "This invoice was generated by Crossed Hearts for your physical book order records.",
    48,
    102,
    { font, maxWidth: 480 },
  );

  return Buffer.from(await pdfDoc.save());
};

module.exports = { buildInvoicePdf, buildPhysicalOrderInvoicePdf };
